Npm fix
arvidsandin/cookie-banner pull request #18
Opened 2023-12-12 08:36 UTC by arvidsandin

* Fix dependencies
* Add publishing script
* Documentation

2023-12-13 12:25 UTC, R0tenur requested changes

2023-12-13 12:25 UTC, R0tenur commented on package.json
> +    "publish": "lerna version --no-private --no-push && npm run publish-angular && npm run publish-react && npm run publish-vue"
If you want to improve speed of this task you can use single &
```sh
npm run publish-angular & npm run publish-react & npm run publish-vue
```
Then the publish commands will run in paralell

2023-12-13 12:41 UTC, arvidsandin commented on package.json
> +    "publish": "lerna version --no-private --no-push && npm run publish-angular && npm run publish-react && npm run publish-vue"
Since npm will prompt a two-factor authentication step for each publish, it's advantageous to have at least one publish run before the others in order to have time to fill in the checkbox "allow publishing without extra authentication for the next 5 minutes"

2023-12-18 14:10 UTC, R0tenur approved these changes

2023-12-19 07:26 UTC, merged