Add "accept", "reject" and "more options" buttons
arvidsandin/cookie-banner pull request #3
Opened 2023-09-14 06:41 UTC by arvidsandin

2023-09-14 09:25 UTC, R0tenur requested changes
Generally, use ```let/const`` for variables instead of ```var```
Why?

```ts
var foo = 'yo';
if(true) {
  var foo = 'nooo'; 
}

console.log(foo); // nooo
```
Can resultat in strange bugs


But:
```ts
let foo = 'yo';
if(true) {
  let foo = 'nooo'; 
}

console.log(foo); // yo
```

2023-09-14 09:25 UTC, R0tenur commented on src/components/ask-manager/ask-manager.spec.ts
> +    var timeBefore = new Date();
const

2023-09-14 09:25 UTC, R0tenur commented on src/components/ask-manager/ask-manager.spec.ts
> +    var timeAfter = new Date();
const

2023-09-14 09:25 UTC, R0tenur commented on src/components/ask-manager/ask-manager.spec.ts
> +  function sleep() {
Testframework is based on jest so the proper way would be to use built in
advanceTimersByTime

2023-09-14 09:25 UTC, R0tenur commented on src/components/ask-manager/ask-manager.css
> +.dimmable-background {
The commonly used name is backdrop

2023-09-14 09:25 UTC, R0tenur commented on src/components/ask-manager/ask-manager.spec.ts
> +describe('my-component', () => {
my-component should probably be ask-manager

2023-09-14 09:25 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
> +  cookieConsent = JSON.parse(localStorage.getItem('cookie-consent')) || {
I it would be a good idea to seperate the state from the view layer. The stencil way seem to be using "stencil store". Is probably easy to attach to localStorage.

2023-09-14 09:25 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
> +    localStorage.setItem(`cookie-consent`, JSON.stringify(this.cookieConsent));
'cookie-consent' is a constant that should be set in it's own reusable variable.

Also that storage-name is probably suitable for an option.

2023-09-14 09:25 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
> +  @Prop() categories: string[] = [];
Consider to set this as an options object. instead. Like ```Partial<CookieOptions>```

And if you make use of properties you could do something like
```ts
private readonly defaultOptions ={...}
private userOptions= {...}
@Prop() set options(value) {
   this.userOptions= {
       ...defaultOptions,
       ...userOptions,
  };
}

2023-09-18 09:49 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
> +  @Prop() categories: string[] = [];
Will be fixed in another pull request

2023-09-18 09:49 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
> +    localStorage.setItem(`cookie-consent`, JSON.stringify(this.cookieConsent));
Will be fixed in another pull request

2023-09-18 09:49 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
> +  cookieConsent = JSON.parse(localStorage.getItem('cookie-consent')) || {
Will be fixed in another pull request

2023-09-18 17:20 UTC, R0tenur commented
Actially let should be const inte the vars are not modified. But I don't have to be that picky

2023-09-19 07:14 UTC, arvidsandin commented
> Actially let should be const inte the vars are not modified

They are set again in line 26 and 30

2023-09-19 07:18 UTC, R0tenur approved these changes

2023-09-19 07:21 UTC, merged

2023-09-20 14:32 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
> +    localStorage.setItem(`cookie-consent`, JSON.stringify(this.cookieConsent));
Solved in #4

2023-09-20 14:32 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
> +  @Prop() categories: string[] = [];
Solved in #4

2023-09-29 09:51 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
> +  cookieConsent = JSON.parse(localStorage.getItem('cookie-consent')) || {
Solved in #6