Add options view
arvidsandin/cookie-banner pull request #4
Opened 2023-09-20 06:24 UTC by arvidsandin

2023-09-20 10:42 UTC, R0tenur requested changes
Generally I would like you to look into the access modifiers on the functions.

public/private etc

2023-09-20 10:42 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
> +    this.acceptCategories(selectedCategories);
Alternative how to write this a bit more compact:
```ts
selectedCategories.filter(o => o.checked).map(o => o.value);
```

This is probably not optimal for the sake of performance, but you will not have that many categories.

If performance is more important:
```ts
selectedCategories.reduce((filtered, option) => {
  if (option.checked) {
     filtered.push(option.value);
  }
  return filtered;
}, []);
```
But then the readability you have now is better

2023-09-20 10:42 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
> +        {this.isInOptionsView ? (
Split into seperate components. 

If not using a framework for selecting what component to show I would consider an object in the component:

```tsx
views = {
  'fullscreen-options': <FullscreenOptions/>, // Pointing to other components
  'bottom-options': <BottomOptions/>,
  etc
}
type View = keyof views;

selectedView: View;

```

Then you could do some conditional rendering by
```html
<div class="dimmable-backdrop">
    {views[selectedView]}
</div>
```

2023-09-20 11:08 UTC, arvidsandin commented
> Generally I would like you to look into the access modifiers on the functions.
> 
> public/private etc

If I make the functions private (which most, if not all should be), they can no longer be executed in the unit tests. I still haven't figured out how to handle that better

2023-09-20 11:47 UTC, R0tenur commented
Generally it's only the public api that should be tested.
The private stuff can be tester based on the  side effects and outcome

2023-09-20 11:48 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
> +        {this.isInOptionsView ? (
Will be fixed in another pull request

2023-09-20 12:58 UTC, R0tenur requested changes

2023-09-20 12:58 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
> +  @Prop() storageName: string = 'cookie-consent';
Would say everything should be part of options

2023-09-20 14:16 UTC, R0tenur approved these changes

2023-09-20 14:31 UTC, merged

2023-09-21 07:15 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
> +        {this.isInOptionsView ? (
Solved in #5