Make text content customizable
arvidsandin/cookie-banner pull request #5
Opened 2023-09-21 07:14 UTC by arvidsandin

2023-09-22 14:20 UTC, R0tenur requested changes
Code looks good in general! Want to try it out on my machine during the weekend

2023-09-22 14:20 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
> +    this.mainTextContent = options.mainTextContent;
This starting to escalate a bit. I would put the options as a class variable and refer to that instead of mapping the fields.

2023-09-22 14:20 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
>      if (this.cookiePolicyLastUpdated == null) {
I would break out this to a ```validateOptions(options)``` function that contained all of the validation stuff regardless of producing warning or errors

2023-09-22 14:20 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
>    async setOptions(userOptions) {
I would type the input.
The most common scenario will be to use this in some kind of framework, then it would be nice if this don't compiles when used wrong with typescript

2023-09-22 14:20 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
>    async setOptions(userOptions) {
Also: Why async?

2023-09-22 14:20 UTC, R0tenur commented on src/components/ask-manager/ask-manager.spec.ts
> -    expect(theAskManager.isInOptionsView).toBeFalsy();
Common way of setting up a unit test is to split it up in three parts:
Arrange, Act, Assert
Or
Given, When, Then

And generally only testing one scenario per test. This will make it much easier to get whats wrong with a test when it fails in the future.

BUT

When tests are more or less the same, but with different data, it's both common and good practice to share the code do the decrease the maintenance.

To get all of the good parts of this you could do like this:

```ts
[
  { 
    linkToPrivacyPolicy: null,
    linkText: 'yoyo',
    errorMessage: 'No linkToPrivacyPolicy provided'
  }  
].foreach(({
  linkToPrivacyPolicy,
  linkText,
  errorMessage
}) => it(`throw ${errorMessage} when linkToPrivacyPolicy is ${linkToPrivacyPolicy} and linktext is ${linkText}`, () => {
// Arrange
const options = {
  cookiePolicyLastUpdated: '2023-01-01',
  linkToPrivacyPolicy,
  linktext, 
}

// Act and assert (since the execution is both here)
expect(theAskManager.setOptions(options)).toThrow(errorMessage);
})).

```
Then the test become somehow "data driven"

Another thing to mention is that you donät nescessary need to test that:
```ts
const foo = undefined;
if(foo)
```

gives the same result as
```ts
const foo = null;
if(foo)

```
Since that is how javascript works. But depending on how your app works there can ofc be exceptions

2023-09-22 14:20 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
> +    rejectText: 'Reject non-essential',
I would put the text in a subobject
```ts
const options = {
  texts: {
      acceptText: 'Accept all',
      ...
   }
}

2023-09-22 14:20 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
> +    rejectText: 'Reject non-essential',
Another thing you might need to think about ahead is the best way to handle multilanguage pages

2023-09-22 14:20 UTC, R0tenur commented on src/components/primary-banner/primary-banner.tsx
> +            {this.mainTextContent.split(this.stringTokenForLink)[0]}
I think you should do this on initialization, connected to set options instead. Otherwise it will do this every time the component rerenders.

2023-09-22 14:20 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
> +            acceptText={this.acceptText}
Need to think about the text handling. Now you need to pass it around everywhere.

If you used some kind of centralized store, the you could have a special TextComponent that took in a
```ts
export Type Language = keyOf TextOptions;
export interface TextOptions {
  mainText: string;
  linkText: string;
  ...
}


<Text text="mainText"/>

2023-09-22 14:32 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
>    async setOptions(userOptions) {
Public methods in Stencil must be async

2023-09-26 09:09 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
> +            acceptText={this.acceptText}
Will be fixed in another pull request

2023-09-26 09:10 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
> +    this.mainTextContent = options.mainTextContent;
Will be fixed in another pull request

2023-09-26 09:10 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
>    async setOptions(userOptions) {
Will be fixed in another pull request

2023-09-29 09:22 UTC, R0tenur approved these changes

2023-09-29 09:48 UTC, merged

2023-09-29 09:51 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
> +            acceptText={this.acceptText}
Solved in #6

2023-10-05 13:27 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
> +    this.mainTextContent = options.mainTextContent;
Solved in #7

2023-10-05 13:28 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
>    async setOptions(userOptions) {
Solved in #7