Hide banner after choice is made
arvidsandin/cookie-banner pull request #6
Opened 2023-09-29 09:50 UTC by arvidsandin

+ Move data to Stencil Store

2023-10-03 07:30 UTC, R0tenur requested changes

2023-10-03 07:30 UTC, R0tenur commented on src/components/primary-banner/primary-banner.tsx
> +        <button onClick={this.acceptAllCookies}>{state.texts.acceptText}</button>
Picky, but now when you have the text object, you don't need text suffix of the keys

2023-10-03 07:30 UTC, R0tenur commented on src/components/more-options-banner/more-options-banner.tsx
> +        {state.categories.map(category => (
```ts
        {state.categories.map((category, index) => (
```

then you don't need to use indexOf below

2023-10-03 07:30 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
> +      <Host style={this.bannerVisible() ? {} : { display: 'none' }}>
Instead of hiding it with css i would not render the component at all

2023-10-03 07:30 UTC, R0tenur commented on src/components/ask-manager/ask-manager.tsx
> +    state.storageName = options.storageName;
Instead of mutating state directly I think it would be more proper to use [store.set](https://stenciljs.com/docs/stencil-store#storesetpropname-value)

2023-10-03 08:50 UTC, arvidsandin commented on src/components/primary-banner/primary-banner.tsx
> +        <button onClick={this.acceptAllCookies}>{state.texts.acceptText}</button>
Will be fixed in another pull request, when options are moved to a separate variable

2023-10-03 08:50 UTC, arvidsandin commented on src/components/ask-manager/ask-manager.tsx
> +    state.storageName = options.storageName;
Will be fixed in another pull request, when options are moved to a separate variable

2023-10-03 09:29 UTC, R0tenur approved these changes

2023-10-03 09:37 UTC, merged

2023-10-05 13:28 UTC, arvidsandin commented on src/components/primary-banner/primary-banner.tsx
> +        <button onClick={this.acceptAllCookies}>{state.texts.acceptText}</button>
Solved in #7