Create API for setting up and polling the component
arvidsandin/cookie-banner pull request #7
Opened 2023-10-05 13:08 UTC by arvidsandin

2023-10-10 09:30 UTC, R0tenur requested changes

2023-10-10 09:30 UTC, R0tenur commented on src/utils/category.ts
> +  adjective?: string;
Not clear what this does

2023-10-10 09:30 UTC, R0tenur commented on README.md
> +customElements.whenDefined('ask-manager').then(() => {
I actually think it would work to do

```html
<script type="module">
    await customElements.whenDefined('ask-mananger');
    document.querySelector('ask-manager').setOptions(options)
</script>

2023-10-10 09:30 UTC, R0tenur commented on README.md
> +### The options object
Consider checking out something like https://www.npmjs.com/package/documentation

2023-10-10 09:30 UTC, R0tenur commented on src/index.html
> +        e.detail.unshift('essential');
I know this is your testing page, but are you adding essential first to the array outside of the component?

2023-10-10 09:30 UTC, R0tenur commented on src/index.html
> +    <button onclick="localStorage.removeItem('cookie-consent')">Delete consent</button>
Do you want this as a exposed function? `deleteConsent()`

2023-10-12 12:01 UTC, arvidsandin commented on src/index.html
> +    <button onclick="localStorage.removeItem('cookie-consent')">Delete consent</button>
I wasn't planning to, but it's actually a good idea

2023-10-12 12:03 UTC, arvidsandin commented on src/index.html
> +        e.detail.unshift('essential');
This was done as a way of (not) handling an empty array in the test page

2023-10-13 09:27 UTC, arvidsandin commented on README.md
> +### The options object
Will be fixed in another pull request

2023-10-16 07:44 UTC, R0tenur approved these changes

2023-10-16 09:00 UTC, merged